### ISSUE TITLE
Keyboard support

### ISSUE THREAD

**Issue by mharmel** [OverflowCat/logseq-pdf-nav#1]
Could you add keyboard shortcuts for the back and forward actions?

If you do: being able to hide the buttons on the pdf toolbar whilst using this plugin via keyboard shortcuts would be nice to keep the UI clean :)

**Comment by OverflowCat** [comment]
[Edited] Logseq now has a good shortcut manager 😃

**Comment by OverflowCat** [comment]
Implemented in #6, kudos to xyhp915 🎉
