### ISSUE TITLE
Version 0.8.18 breaks this plugin

### ISSUE THREAD

**Issue by m-yaghini** [OverflowCat/logseq-pdf-nav#3]
The navigation buttons does not work anymore in this version. 

Note that this version has introduced a revamped PDF reader (with a detachable window, highlighted markups and what not) so it's not surprising that this breaks this plugin.

**Comment by OverflowCat** [comment]
Thank you for your feedback. This is caused by [this commit](https://github.com/logseq/logseq/commit/55b5149f4a156a1f741b1b8444c719e788692066#diff-ac31f0ac3fab94e5aa923a0b5dfcc19c1d08689fbf74074ec9879093ad80c3caR741-R753). Hope my fix (0.1.3) will work.
